version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: .lazycat-build/opencloud.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: opencloud

build:
  run_buildscript: false

images:
  - id: opencloud
    target: service
    service: opencloud
    source: opencloudeu/opencloud-rolling
    channel: stable
    sort: semver
    tag_regex: '^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'
    version_regex: '^(?P<version>(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*))$'
    version_template: '{version}'
    delivery:
      mode: mirror
      require_digest_match: true

stores:
  official:
    enabled: false
    continue_if_newer_version: true
    skip_if_version_exists: false
    retry:
      enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: OpenCloud
    summary: Open source file management, sharing and collaboration.
