package: community.lazycat.app.opencloud
version: 8.1.0
name: OpenCloud
description: "\U0001F324️ OpenCloud is the open source platform for file management, sharing and collaboration. Simple and sovereign."
author: opencloud-eu
license: Apache-2.0
homepage: https://github.com/opencloud-eu/opencloud
min_os_version: 1.5.0
permissions:
  required:
    - net.internet
locales:
  zh:
    name: OpenCloud
    description: "\U0001F324️ OpenCloud 是用于文件管理、共享与协作的开源平台，简洁且自主可控。"
  en:
    name: OpenCloud
    description: "\U0001F324️ OpenCloud is the open source platform for file management, sharing and collaboration. Simple and sovereign."
